#!/usr/bin/env bash
# This script that creates the file /var/run/myscript.pid containing its PID
echo "$$" > /var/run/myscript.pid

delfunc() {
	rm /var/run/myscript.pid
	exit
}

while true;
do
	echo "To infinity and beyond";
	sleep 2
	trap 'echo "Y U no love me?!"' SIGINT
	trap 'echo "I hate the kill command" && delfunc' SIGTERM
	trap 'delfunc' SIGQUIT
done
