#!/usr/bin/env bash
# This script that displays the content of the file /etc/passwd, using the while loop + IFS.
file="/etc/passwd";
while IFS= read -r line;
do
	username="$(echo "$line" | cut -d":" -f1)";
	grp_id="$(echo "$line" | cut -d":" -f4)";
	home_dir="$(echo "$line" | cut -d":" -f6)";
	shell="$(echo "$line" | cut -d":" -f7)";
	user_id="$(echo "$line" | cut -d":" -f3)";
	password="$(echo "$line" | cut -d":" -f2)";
	user_id_info="$(echo "$line" | cut -d":" -f5)";
	echo "The user ${username} is part of the ${grp_id} gang, lives in ${home_dir} and rides ${shell}. ${user_id}'s place is protected by the passcode ${password}, more info about the user here: ${user_id_info}";
done < "$file";
